# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lq0yCAhn8FyiarEI5X5JSdVwaCO1ZVO1
"""

# Exploratory Data Analysis (EDA) for Fertilizer Recommendation
import pandas as pd
import matplotlib.pyplot as plt

# Example placeholder dataset
# df = pd.read_csv("../data/fertilizer_dataset.csv")
# df.head()